// Static game data: TRA lines, scenery themes, rolling stock.
// Station tuples: [中文, English, major(1/0), theme of the section arriving at this station, wooden station]

const S = (zh, en, major, theme, wooden = 0) => ({ zh, en, major: !!major, theme, wooden: !!wooden });

export const LINES = [
  {
    id: 'western',
    zh: '縱貫線（北段）',
    en: 'Western Line · North',
    desc: '臺北都會區到竹塹平原。密集的街屋、平交道與大站。',
    descEn: 'From the Taipei metro area to the Hsinchu plain. Dense townhouses, crossings and big stations.',
    double: true,
    oceanSide: 0,
    vmax: 130,
    baseY: 22,
    stations: [
      S('臺北', 'Taipei', 1, 'urban'),
      S('萬華', 'Wanhua', 1, 'urban'),
      S('板橋', 'Banqiao', 1, 'urban'),
      S('浮洲', 'Fuzhou', 0, 'urban'),
      S('樹林', 'Shulin', 1, 'urban'),
      S('南樹林', 'Nanshulin', 0, 'suburban'),
      S('山佳', 'Shanjia', 0, 'suburban'),
      S('鶯歌', 'Yingge', 0, 'suburban'),
      S('鳳鳴', 'Fengming', 0, 'suburban'),
      S('桃園', 'Taoyuan', 1, 'urban'),
      S('內壢', 'Neili', 0, 'urban'),
      S('中壢', 'Zhongli', 1, 'urban'),
      S('埔心', 'Puxin', 0, 'suburban'),
      S('楊梅', 'Yangmei', 0, 'suburban'),
      S('富岡', 'Fugang', 0, 'rural'),
      S('新富', 'Xinfu', 0, 'rural'),
      S('北湖', 'Beihu', 0, 'rural'),
      S('湖口', 'Hukou', 0, 'rural'),
      S('新豐', 'Xinfeng', 0, 'rural'),
      S('竹北', 'Zhubei', 1, 'suburban'),
      S('北新竹', 'North Hsinchu', 0, 'urban'),
      S('新竹', 'Hsinchu', 1, 'urban'),
    ],
  },
  {
    id: 'coast',
    zh: '海線',
    en: 'Coast Line',
    desc: '沿著臺灣海峽南下，風車、稻田與日式木造小站。',
    descEn: 'South along the Taiwan Strait: wind turbines, paddies and wooden Japanese-era halts.',
    double: true,
    oceanSide: 1,
    vmax: 130,
    baseY: 12,
    stations: [
      S('竹南', 'Zhunan', 1, 'suburban'),
      S('談文', 'Tanwen', 0, 'coastPlain', 1),
      S('大山', 'Dashan', 0, 'coastPlain', 1),
      S('後龍', 'Houlong', 1, 'coastPlain'),
      S('龍港', 'Longgang', 0, 'coastPlain'),
      S('白沙屯', 'Baishatun', 0, 'coastPlain'),
      S('新埔', 'Xinpu', 0, 'coastPlain', 1),
      S('通霄', 'Tongxiao', 1, 'coastPlain'),
      S('苑裡', 'Yuanli', 1, 'coastPlain'),
      S('日南', 'Rinan', 0, 'rural', 1),
      S('大甲', 'Dajia', 1, 'suburban'),
      S('臺中港', 'Taichung Port', 0, 'rural'),
      S('清水', 'Qingshui', 1, 'suburban'),
      S('沙鹿', 'Shalu', 1, 'suburban'),
      S('龍井', 'Longjing', 0, 'rural'),
      S('大肚', 'Dadu', 0, 'rural'),
      S('追分', 'Zhuifen', 0, 'rural', 1),
      S('彰化', 'Changhua', 1, 'urban'),
    ],
  },
  {
    id: 'yilan',
    zh: '宜蘭線',
    en: 'Yilan Line',
    desc: '基隆河谷的山區隧道，接著太平洋海岸與蘭陽平原。',
    descEn: 'Mountain tunnels along the Keelung River, then the Pacific coast and the Lanyang plain.',
    double: true,
    oceanSide: -1,
    vmax: 130,
    baseY: 14,
    stations: [
      S('八堵', 'Badu', 1, 'suburban'),
      S('暖暖', 'Nuannuan', 0, 'mountain'),
      S('四腳亭', 'Sijiaoting', 0, 'mountain'),
      S('瑞芳', 'Ruifang', 1, 'mountain'),
      S('猴硐', 'Houtong', 0, 'mountain'),
      S('三貂嶺', 'Sandiaoling', 0, 'mountain'),
      S('牡丹', 'Mudan', 0, 'mountain'),
      S('雙溪', 'Shuangxi', 0, 'mountain'),
      S('貢寮', 'Gongliao', 0, 'mountain'),
      S('福隆', 'Fulong', 1, 'mountain'),
      S('石城', 'Shicheng', 0, 'coast'),
      S('大里', 'Dali', 0, 'coast'),
      S('大溪', 'Daxi', 0, 'coast'),
      S('龜山', 'Guishan', 0, 'coast'),
      S('外澳', "Wai'ao", 0, 'coast'),
      S('頭城', 'Toucheng', 1, 'coast'),
      S('頂埔', 'Dingpu', 0, 'lanyang'),
      S('礁溪', 'Jiaoxi', 1, 'lanyang'),
      S('四城', 'Sicheng', 0, 'lanyang'),
      S('宜蘭', 'Yilan', 1, 'suburban'),
      S('二結', 'Erjie', 0, 'lanyang'),
      S('中里', 'Zhongli', 0, 'lanyang'),
      S('羅東', 'Luodong', 1, 'suburban'),
      S('冬山', 'Dongshan', 0, 'lanyang'),
      S('新馬', 'Xinma', 0, 'lanyang'),
      S('蘇澳新', "Su'aoxin", 1, 'lanyang'),
    ],
  },
  {
    id: 'huatung',
    zh: '花東線',
    en: 'Hualien–Taitung Line',
    desc: '花東縱谷：中央山脈與海岸山脈之間一望無際的稻田。',
    descEn: 'The East Rift Valley: endless paddies between the Central and Coastal ranges.',
    double: true,
    oceanSide: 0,
    vmax: 130,
    baseY: 60,
    stations: [
      S('花蓮', 'Hualien', 1, 'suburban'),
      S('吉安', "Ji'an", 0, 'suburban'),
      S('志學', 'Zhixue', 0, 'valley'),
      S('平和', 'Pinghe', 0, 'valley'),
      S('壽豐', 'Shoufeng', 0, 'valley'),
      S('豐田', 'Fengtian', 0, 'valley'),
      S('林榮新光', 'Linrong Shin Kong', 0, 'valley'),
      S('南平', 'Nanping', 0, 'valley'),
      S('鳳林', 'Fenglin', 1, 'valley'),
      S('萬榮', 'Wanrong', 0, 'valley'),
      S('光復', 'Guangfu', 1, 'valley'),
      S('大富', 'Dafu', 0, 'valley'),
      S('富源', 'Fuyuan', 0, 'valley'),
      S('瑞穗', 'Ruisui', 1, 'valley'),
      S('三民', 'Sanmin', 0, 'mountain'),
      S('玉里', 'Yuli', 1, 'valley'),
      S('東里', 'Dongli', 0, 'valley'),
      S('東竹', 'Dongzhu', 0, 'valley'),
      S('富里', 'Fuli', 0, 'valley'),
      S('池上', 'Chishang', 1, 'valley'),
      S('海端', 'Haiduan', 0, 'valley'),
      S('關山', 'Guanshan', 1, 'valley'),
      S('瑞和', 'Ruihe', 0, 'valley'),
      S('瑞源', 'Ruiyuan', 0, 'valley'),
      S('鹿野', 'Luye', 0, 'valley'),
      S('山里', 'Shanli', 0, 'mountain'),
      S('臺東', 'Taitung', 1, 'suburban'),
    ],
  },
  {
    id: 'southlink',
    zh: '南迴線',
    en: 'South-Link Line',
    desc: '單線山岳路線，連續隧道與陡坡，太平洋就在右手邊。',
    descEn: 'Single-track mountain line with tunnels and steep grades — the Pacific on your right.',
    double: false,
    oceanSide: 1,
    vmax: 110,
    baseY: 14,
    stations: [
      S('枋寮', 'Fangliao', 1, 'rural'),
      S('加祿', 'Jialu', 0, 'coast'),
      S('內獅', 'Neishi', 0, 'coast'),
      S('枋山', 'Fangshan', 0, 'coast'),
      S('大武', 'Dawu', 1, 'mountain'),
      S('瀧溪', 'Longxi', 0, 'coast'),
      S('金崙', 'Jinlun', 1, 'coast'),
      S('太麻里', 'Taimali', 1, 'coast'),
      S('知本', 'Zhiben', 1, 'coast'),
      S('康樂', 'Kangle', 0, 'rural'),
      S('臺東', 'Taitung', 1, 'suburban'),
    ],
  },
];

// Scenery / alignment themes. Distances in metres, grade in ‰.
// mount: mountains flanking the line {a: amplitude, dist: start distance, ramp: rise distance}
export const THEMES = {
  urban: {
    interstation: [1400, 2400], curveR: [600, 1600], turn: [5, 30], straight: [300, 1200], grade: 6,
    relief: 2, mount: { a: 60, dist: 1400, ramp: 1200 },
    bld: 1.0, tall: 0.5, paddy: 0.0, tree: 0.25, palm: 0.03, forest: 0, wall: 0.8, turbine: 0,
    crossing: 0.35, river: 0.35, riverW: [60, 220], riverDepth: [6, 8], tunnel: 0,
    ground: [0.44, 0.45, 0.38],
  },
  suburban: {
    interstation: [1800, 3000], curveR: [700, 2000], turn: [5, 35], straight: [300, 1400], grade: 8,
    relief: 4, mount: { a: 120, dist: 1100, ramp: 1200 },
    bld: 0.55, tall: 0.15, paddy: 0.3, tree: 0.45, palm: 0.15, forest: 0.1, wall: 0.3, turbine: 0,
    crossing: 0.5, river: 0.45, riverW: [60, 260], riverDepth: [6, 8], tunnel: 0,
    ground: [0.40, 0.48, 0.30],
  },
  rural: {
    interstation: [2200, 4000], curveR: [800, 2500], turn: [5, 35], straight: [400, 1600], grade: 6,
    relief: 3, mount: { a: 200, dist: 1500, ramp: 1500 },
    bld: 0.16, tall: 0, paddy: 0.85, tree: 0.5, palm: 0.5, forest: 0.1, wall: 0, turbine: 0,
    crossing: 0.6, river: 0.5, riverW: [80, 400], riverDepth: [6, 8], tunnel: 0,
    ground: [0.38, 0.50, 0.26],
  },
  coastPlain: {
    interstation: [2200, 3800], curveR: [800, 2000], turn: [5, 30], straight: [400, 1500], grade: 5,
    relief: 3, coast: 200, maxY: 18, landMount: { a: 70, dist: 220, ramp: 500 },
    bld: 0.15, tall: 0, paddy: 0.45, tree: 0.35, palm: 0.25, forest: 0.15, wall: 0, turbine: 1,
    crossing: 0.45, river: 0.45, riverW: [80, 300], riverDepth: [5, 7], tunnel: 0.05,
    ground: [0.46, 0.50, 0.30],
  },
  coast: {
    interstation: [2600, 4200], curveR: [420, 900], turn: [10, 55], straight: [150, 700], grade: 12,
    relief: 3, coast: 55, maxY: 22, landMount: { a: 360, dist: 60, ramp: 380 },
    bld: 0.12, tall: 0, paddy: 0.08, tree: 0.3, palm: 0.25, forest: 1, wall: 0, turbine: 0,
    crossing: 0.15, river: 0.5, riverW: [40, 140], riverDepth: [7, 12], tunnel: 0.4,
    ground: [0.36, 0.48, 0.26],
  },
  mountain: {
    interstation: [3000, 5200], curveR: [380, 800], turn: [15, 100], straight: [120, 600], grade: 18,
    relief: 8, mount: { a: 380, dist: 40, ramp: 420 },
    bld: 0.05, tall: 0, paddy: 0.02, tree: 0.2, palm: 0.1, forest: 1, wall: 0, turbine: 0,
    crossing: 0.05, river: 0.7, riverW: [25, 90], riverDepth: [14, 30], tunnel: 0.65,
    ground: [0.30, 0.42, 0.22],
  },
  valley: {
    interstation: [2400, 4400], curveR: [900, 2500], turn: [4, 25], straight: [500, 2000], grade: 5,
    relief: 3, mount: { a: 900, dist: 900, ramp: 1100 },
    bld: 0.1, tall: 0, paddy: 0.9, tree: 0.4, palm: 0.45, forest: 0.4, wall: 0, turbine: 0,
    crossing: 0.5, river: 0.55, riverW: [120, 500], riverDepth: [5, 7], tunnel: 0,
    ground: [0.38, 0.52, 0.26],
  },
  lanyang: {
    interstation: [2000, 3600], curveR: [900, 2500], turn: [4, 25], straight: [500, 1800], grade: 4,
    relief: 2, landMount: { a: 700, dist: 1300, ramp: 900 }, flatSea: true,
    bld: 0.2, tall: 0, paddy: 0.9, tree: 0.35, palm: 0.2, forest: 0.3, wall: 0, turbine: 0,
    crossing: 0.6, river: 0.5, riverW: [80, 300], riverDepth: [5, 7], tunnel: 0,
    ground: [0.38, 0.52, 0.26],
  },
};

export const TRAINS = {
  EMU800: {
    id: 'EMU800',
    zh: '區間車',
    en: 'Local',
    model: 'EMU800',
    type: 'local',
    cars: 8,
    carLen: 20,
    vmax: 110,
    accel: 3.0, // km/h/s
    vBase: 50, // km/h, constant-power region above
    brake: 4.0, // B8 service, km/h/s
    eb: 4.8,
    tilt: false,
    dwell: 25,
    noseLen: 1.2,
    desc: '每站停車。加速快，最高速 110 km/h。',
    descEn: 'Stops everywhere. Quick acceleration, 110 km/h top speed.',
    livery: { body: '#eef0f0', window: '#1d242b', stripe: '#f5b800', stripe2: '#1d242b', door: '#f5b800', front: '#f5b800', roof: '#b9bdbf' },
  },
  EMU3000: {
    id: 'EMU3000',
    zh: '新自強號',
    en: 'Tze-Chiang Ltd. Express',
    model: 'EMU3000',
    type: 'express',
    cars: 12,
    carLen: 20,
    vmax: 130,
    accel: 2.5,
    vBase: 60,
    brake: 3.8,
    eb: 4.6,
    tilt: false,
    dwell: 40,
    noseLen: 2.6,
    desc: '只停大站，最高速 130 km/h，12 節編組。',
    descEn: 'Major stations only. 130 km/h, 12 cars long.',
    livery: { body: '#f4f5f5', window: '#23282e', stripe: '#ef6a1f', stripe2: '#6b7178', door: '#dfe2e4', front: '#f4f5f5', roof: '#c3c7ca' },
  },
  TEMU2000: {
    id: 'TEMU2000',
    zh: '普悠瑪號',
    en: 'Puyuma Express',
    model: 'TEMU2000',
    type: 'express',
    cars: 8,
    carLen: 20,
    vmax: 130,
    accel: 2.4,
    vBase: 65,
    brake: 3.8,
    eb: 4.6,
    tilt: true,
    dwell: 40,
    noseLen: 3.6,
    desc: '傾斜式列車，彎道限速較高。只停大站。',
    descEn: 'Tilting train: higher curve limits. Major stations only.',
    livery: { body: '#f6f6f6', window: '#1b1e22', stripe: '#d3151c', stripe2: '#d3151c', door: '#f6f6f6', front: '#d3151c', roof: '#c9cbcd' },
  },
  E1000: {
    id: 'E1000',
    zh: '自強號 (推拉式)',
    en: 'Push-pull Tze-Chiang',
    model: 'E1000',
    type: 'express',
    cars: 10,
    carLen: 20,
    vmax: 130,
    noseLen: 2.0,
    livery: { body: '#f0f0ec', window: '#262b30', stripe: '#e8541e', stripe2: '#f0a51e', door: '#f0f0ec', front: '#e8541e', roof: '#b8bbb8' },
  },
};

export const PLAYER_TRAINS = ['EMU800', 'EMU3000', 'TEMU2000'];

// Curve speed limit (km/h) for radius R (m); tilting trains get ~16 % more.
export function curveLimit(R, tilt) {
  const c = tilt ? 0.84 : 0.62;
  const v = 3.6 * Math.sqrt(R * c);
  return Math.max(35, Math.floor(v / 5) * 5);
}

export const ASPECT_LIMIT = [0, 45, 75, 999]; // R, Y, YG, G
export const ASPECT_NAME = ['R', 'Y', 'YG', 'G'];

export const DIFFICULTY = {
  easy: { zh: '簡單', en: 'Easy', life: 60, events: 1, slack: 1.12 },
  normal: { zh: '普通', en: 'Normal', life: 40, events: 2, slack: 1.07 },
  hard: { zh: '困難', en: 'Hard', life: 25, events: 3, slack: 1.035 },
};

export const TIMES = {
  day: { zh: '白天', en: 'Day' },
  dusk: { zh: '黃昏', en: 'Dusk' },
  night: { zh: '夜晚', en: 'Night' },
};
